project:
  type: book
  output-dir: _book
  
execute:
  freeze: auto
  dir: book/../

book:
  title: "Applied Geodata Science 2"
  subtitle: "Introducing applications of machine learning in Geography and Environmental Sciences"
  author: "Benjamin Stocker and Fabian Bernhard"
  date: "12 September 2025"
  page-navigation: true
  chapters:
    - index.qmd
    - logistics.qmd
    - plan.qmd
    - leaderboard_fall_2025.qmd
    - leaderboard_fLUE_fall_2025.qmd
    - references.qmd
  favicon: "figures/favicon.ico"
  twitter-card: true
  search: true
  repo-url: https://github.com/geco-bern/agds2_course
  sharing: [twitter, facebook]
  navbar:
    logo: "images/logo.png"
    background: "#3A3A3A"
    search: true
    right:
      - text: "Home"
        file: index.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
